### ISSUE TITLE
Accept command line options in ros-run

### ISSUE THREAD

**Issue by ehuang3** [code-iai/ros_emacs_utils#11]
See title.

**Comment by gaya-** [comment]
It is possible to have arguments for rosrun using [Emacs command prefix arguments](https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html)
(default key binding is ```C-u```).

It will be something like:
```C-u C-x C-r C-r rospy_tutorials RET talker RET  chatter:=/namespace/chatter```

Would that solve the issue?

**Comment by ehuang3** [comment]
Yes, that works. I wasn't aware that it accepted prefix arguments. Thanks!
