### ISSUE TITLE
Kinetic release?

### ISSUE THREAD

**Issue by jack-oquin** [code-iai/ros_emacs_utils#18]
Many thanks for providing these packages!

Would you consider releasing them to Kinetic?

**Comment by gaya-** [comment]
It's on my ToDo list, thanks for the reminder! It is in fact time to get around this, I'll try to initiate the release this week.

**Comment by jack-oquin** [comment]
Much appreciated!

**Comment by gaya-** [comment]
Tested it from the shadow-fixed on my brand new 16.04. Seems to work fine. Should be there with the next sync.

**Comment by jack-oquin** [comment]
Thanks! I've been using rosemacs for years, and have gotten spoiled by it. :smile:

**Comment by gaya-** [comment]
Could we close this issue? Looks like things work fine on Kinetic atm.

**Comment by jack-oquin** [comment]
Sure. Works for me.
