### ISSUE TITLE
Release ros_emacs_utils into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [code-iai/ros_emacs_utils#29]
Would you mind releasing `ros_emacs_utils` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 13 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by gaya-** [comment]
We don't have Python code in rosemacs but this particular package I absolutely cannot release untested. Would it be possible to test it in the upcoming Ubuntu 20.04? If so, I would do that as soon as it is available. But, preferably, not before.

**Comment by sloretz** [comment]
> Would it be possible to test it in the upcoming Ubuntu 20.04? If so, I would do that as soon as it is available. But, preferably, not before.

[Ubuntu Focal is available](https://releases.ubuntu.com/20.04/).

I also recommend testing before release using a dev job on the ROS build farm. All that's needed is a source entry in `ros/rosdistro`. Here's an example where the `ros_controllers` maintainer added a source entry: https://github.com/ros/rosdistro/pull/24553 and now there's a job on the ROS 1 build farm: http://build.ros.org/view/Ndev/job/Ndev__ros_controllers__ubuntu_focal_amd64/

**Comment by gaya-** [comment]
The PR is out. `rosemacs` seems to be working well on 20.04. `roslisp_repl` has some non-critical issues. But as 99% of users only use the `rosemacs` package, I decided to release the whole thing now and fix minor problems of `roslisp_repl` later.

**Comment by sloretz** [comment]
Thanks for the releases :tada: https://github.com/ros/rosdistro/pull/25030 https://github.com/ros/rosdistro/pull/25046
