### ISSUE TITLE
Install fails due to conflict with existing emacs26 setup

### ISSUE THREAD

**Issue by antoan** [code-iai/ros_emacs_utils#30]
ROS Melodic, Ubuntu 18.04

[rosemacs_install_log.txt](https://github.com/code-iai/ros_emacs_utils/files/4736229/rosemacs_install_log.txt)

dpkg: error processing archive /tmp/apt-dpkg-install-QSPfWD/0-emacs25-common_25.3~2.gitc09215a-kk1+18.04_all.deb (--unpack):
 trying to overwrite '/usr/share/emacs/site-lisp/subdirs.el', which is also in package emacs26-common 26.3~1.git96dd019-kk1+18.04

Is there a reason why rosemacs has to be bundled with emacs25? Would be grateful for any suggestions for a fix/workaround.

Cheers.

**Comment by gaya-** [comment]
Hi,

The dependency is not emacs25 but emacs:

https://github.com/code-iai/ros_emacs_utils/blob/master/rosemacs/package.xml#L13

Where emacs translates to ``sudo apt install emacs`` for Ubuntu:

https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L730

So it's bundled with the default Emacs version of the operating system.
If you're good with Linux, you can probably reconfigure your Ubuntu to understand emacs26 when saying emacs. But I haven't looked into this myself...

HTH

**Comment by gaya-** [comment]
You could try to add the emacs ppa to your sources list, then you'll always get the newest version of Emacs:

http://ubuntuhandbook.org/index.php/2019/02/install-gnu-emacs-26-1-ubuntu-18-04-16-04-18-10/

I'm not sure if it will overwrite the default for ``emacs`` to ``emacs26`` though.

But, yeah, I'd go with something like this.
