### ISSUE TITLE
Yasnippets from Debian packages under Ubuntu 12.04

### ISSUE THREAD

**Issue by gheorghelisca** [code-iai/ros_emacs_utils#8]
I tried:
1. yasnippet from debian package
2. rosrun roslisp_repl roslisp_repl

I got:

Symbol's function definition is void: yas-global-mode

**Comment by bbrieber** [comment]
The debian version of yasnippet in 14.04 seems to make problems to 
had to deinstall it to get `slime-ros` running

**Comment by gaya-** [comment]
solved in 3e68557.
